import { CountryConfig, HeadFreightConfig } from './types';

export const COUNTRY_CONFIGS: CountryConfig[] = [
  {
    bizCode: "AMZ-US",
    country: "US",
    platform: "Amazon",
    category: "Sports & Outdoors",
    currency: "USD",
    referralFeeRate: 0.15,
    storageOtherRate: 0.01,
    defaultReturnRate: 0.03,
    defaultAffiliateRate: 0,
    lastMileRule: "AMZ_US_FBA",
  },
  {
    bizCode: "AMZ-JP",
    country: "JP",
    platform: "Amazon",
    category: "Sports & Outdoors",
    currency: "USD",
    referralFeeRate: 0.10,
    storageOtherRate: 0.01,
    defaultReturnRate: 0.03,
    defaultAffiliateRate: 0,
    lastMileRule: "AMZ_JP_FBA",
  },
  {
    bizCode: "AMZ-EU",
    country: "EU",
    platform: "Amazon",
    category: "Sports & Outdoors",
    currency: "USD",
    referralFeeRate: 0.15,
    storageOtherRate: 0.01,
    defaultReturnRate: 0.03,
    defaultAffiliateRate: 0,
    lastMileRule: "AMZ_EU_FBA",
  },
  {
    bizCode: "TK-US",
    country: "US",
    platform: "TikTok",
    category: "Sports / Fitness",
    currency: "USD",
    referralFeeRate: 0.06,
    storageOtherRate: 0.025,
    defaultReturnRate: 0.05,
    defaultAffiliateRate: 0.10,
    lastMileRule: "TTS_US_Standard",
  },
  {
    bizCode: "TK-EU",
    country: "EU",
    platform: "TikTok",
    category: "Sports / Fitness",
    currency: "USD",
    referralFeeRate: 0.09,
    storageOtherRate: 0.025,
    defaultReturnRate: 0.05,
    defaultAffiliateRate: 0.10,
    lastMileRule: "TTS_EU_Standard",
  },
];

export const HEAD_FREIGHT_CONFIGS: HeadFreightConfig[] = [
  { bizCode: "AMZ-US", ratePerCbm: 230, unit: "CBM" },
  { bizCode: "TK-US", ratePerCbm: 135, unit: "CBM" },
  { bizCode: "AMZ-EU", ratePerCbm: 180, unit: "CBM" },
  { bizCode: "TK-EU", ratePerCbm: 180, unit: "CBM" },
  { bizCode: "AMZ-JP", ratePerCbm: 80, unit: "CBM" },
];
